---
ansible-navigator:
  execution-environment:
    image: registry.redhat.io/ansible-automation-platform-22/ee-supported-rhel8:latest
    pull:
      policy: missing
  playbook-artifact:
    enable: false
